### ISSUE TITLE
Round forecast times

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-production#31]
## Detailed Description
Would be good to have forecasts that are rounded to mins, 6.05 to 6.10, currently they 06:03:17 to 06:08:17

## Context
We want regular forecast value times

## Possible Implementation
im not sure where, but somewhere, we must use datetime.utcnow(), and we should then round that down to the nearest 5 mins

**Comment by simlmx** [comment]
The caller can already specify a date using `--date`.
Either the caller does it or we add another option like `--round-to-minute 5`, where we would use the closest date before "now" (or `--date` if it is specified).
I don't think we should do it by default however.

**Comment by peterdudfield** [comment]
yea, please add `--round-to-minute 5`, then that allows us to be flexible to 30 mintues for example
