### ISSUE TITLE
Check forecast vs actual

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-production#32]
## Detailed Description
From the database, check that the forecast values are roughly the same order of magnitude than the actual generation values. 
They might not be because of normalisation in the ml modelling code

**Comment by peterdudfield** [comment]
Did you say this is done @simlmx? A quick plot of predictions vs actual would be nice

**Comment by simlmx** [comment]
I had a quick peek but didn't check in detail. I will make a couple plots and share here.

**Comment by peterdudfield** [comment]
Ill close this for the moment, we can see this on vercel now - https://nowcasting-1y2wnnu8a-openclimatefix.vercel.app/
