### ISSUE TITLE
Move old forecast data

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-production#48]
## Detailed Description
Move forecast data older than 3 days to s3

## Context
- this keeps database fast
- means we dont lose any data

## Possible Implementation
- write new entr point in this repo that gets the data, saves it o s3, then deteles it from the database
- terraform can make it run once a day

**Comment by peterdudfield** [comment]
Now deployed on ECS, but get the following error `/bin/sh: 1: [poetry,: not found`

@simlmx would you be able to look at this?

ECS task: https://eu-west-1.console.aws.amazon.com/ecs/v2/task-definitions/database_clean_up/1/json?region=eu-west-1
cloudwatch: https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Fecs$252Fdatabase_clean_up$252F/log-events/streaming$252Fdatabase_clean_up$252Fb7f8ac56ff794deebb1000711a0321dc

**Comment by peterdudfield** [comment]
I think it might need a fix on https://github.com/openclimatefix/pv-site-production/blob/main/infrastructure/Dockerfile.database-cleanup

Maybe adding -date to default to 3 days before 0 I will make a PR for this

**Comment by simlmx** [comment]
Fixed and it works in the Dev environment now.
