### ISSUE TITLE
Upgrade to SQLalchemy >2.0

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-production#79]
## Detailed Description
This can be done using https://github.com/openclimatefix/pv-site-datamodel/issues/88
and pv-site-datamodel==1.0.17

## Context
- sqlalmacy upgrades should make things faster

## Possible Implementation
upgrade requirements and run tests

**Comment by rahul-maurya11b** [comment]
@peterdudfield sir, can you please assign me this issue I have just created a PR for a similar issue.

**Comment by rahul-maurya11b** [comment]
@peterdudfield  sir, I am getting 2 errors while running `make all` : Error : `# Make sure the date of `.venv` is after `pyproject.toml`
process_begin: CreateProcess(NULL, # Make sure the date of `.venv` is after `pyproject.toml`, ...) failed.`


and while running `make all -j 8` : Error : => `ERROR [11/13] RUN poetry install --without dev --no-root                                                     2.0s 
------
 > [11/13] RUN poetry install --without dev --no-root:
1.779 The currently activated Python version 3.10.14 is not supported by the project (^3.11).
1.779 Trying to find and use a compatible version.
1.886
1.886 Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.`

I made the changes based on the poetry lock and poetry errors. Please see this PR #80  for changes.
